name: ci

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Configure
        run: cmake --preset windows-msvc-debug
      - name: Build
        run: cmake --build --preset windows-msvc-debug
      - name: Test
        run: ctest --preset windows-msvc-debug
